### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'is_Float'

### ISSUE THREAD

**Issue by wukan1986** [wukan1986/expr_codegen#25]
```python
def _code_block_3():
    cond_1 = cs_rank(-amount, False)
    close_rank = cs_rank(if_else(cond_1 <= 10, CLOSE, None), False)

df = codegen_exec(df, _code_block_3)
```
报错
```
Traceback (most recent call last):
  File "D:\GitHub\alpha_examples\data\1_prepare_data_test.py", line 66, in <module>
    df = codegen_exec(df, _code_block_3)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Kan\miniconda3\envs\py311_1\Lib\site-packages\expr_codegen\tool.py", line 296, in codegen_exec
    code = _TOOL_._get_code(
           ^^^^^^^^^^^^^^^^^
  File "D:\Users\Kan\miniconda3\envs\py311_1\Lib\site-packages\expr_codegen\tool.py", line 233, in _get_code
    raw, exprs_dict = sources_to_exprs(self.globals_, source, *more_sources, safe=False)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Kan\miniconda3\envs\py311_1\Lib\site-packages\expr_codegen\codes.py", line 246, in sources_to_exprs
    exprs_dict = dict_to_exprs(assigns, globals_, safe)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Kan\miniconda3\envs\py311_1\Lib\site-packages\expr_codegen\expr.py", line 48, in dict_to_exprs
    exprs_src = {k: safe_eval(v, globals_, k, safe) for k, v in exprs_src.items()}
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Kan\miniconda3\envs\py311_1\Lib\site-packages\expr_codegen\expr.py", line 48, in <dictcomp>
    exprs_src = {k: safe_eval(v, globals_, k, safe) for k, v in exprs_src.items()}
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Kan\miniconda3\envs\py311_1\Lib\site-packages\expr_codegen\expr.py", line 69, in safe_eval
    return eval(code, globals_)
           ^^^^^^^^^^^^^^^^^^^^
  File "<user input>", line 1, in <module>
  File "D:\Users\Kan\miniconda3\envs\py311_1\Lib\site-packages\sympy\core\function.py", line 832, in __new__
    obj = super().__new__(cls, *args, **options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Kan\miniconda3\envs\py311_1\Lib\site-packages\sympy\core\cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Kan\miniconda3\envs\py311_1\Lib\site-packages\sympy\core\function.py", line 468, in __new__
    _should_evalf = [cls._should_evalf(a) for a in result.args]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Kan\miniconda3\envs\py311_1\Lib\site-packages\sympy\core\function.py", line 468, in <listcomp>
    _should_evalf = [cls._should_evalf(a) for a in result.args]
                     ^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Kan\miniconda3\envs\py311_1\Lib\site-packages\sympy\core\function.py", line 490, in _should_evalf
    if arg.is_Float:
       ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'is_Float'
```

**Comment by wukan1986** [comment]
0.8.1版中已经进行了更新，通过将`None`替换成`_NONE_`解决
